language: node_js

node_js:
  - 'node'

script:
  - npm run lint
  - npm run test
  - npm run build

notifications:
  email: false

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  local-dir: build
  github-token: $GITHUB_TOKEN
  on:
    branch: master
