export const PROJECTS_FETCH_START = 'PROJECTS_FETCH_START';
export const PROJECTS_FETCH_SUCCESS = 'PROJECTS_FETCH_SUCCESS';
export const PROJECTS_FETCH_ERROR = 'PROJECTS_FETCH_ERROR';

export const AUTHOR_FETCH_START = 'AUTHOR_FETCH_START';
export const AUTHOR_FETCH_SUCCESS = 'AUTHOR_FETCH_SUCCESS';
export const AUTHOR_FETCH_ERROR = 'AUTHOR_FETCH_ERROR';
